# Define workflow name.
name: Test

on:
  workflow_dispatch:

jobs:
  matrixone-ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Print Hostname
        run: |
          ldd --version
          sudo hostnamectl hostname matrixone-upgrade-runner;
          hostname;
          echo ${{ runner.name }}
