# Define workflow name.
name: Test

on:
  workflow_dispatch:

jobs:
  matrixone-ci:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          cd $GITHUB_WORKSPACE;
          echo "aaaaa" > a.txt;
          echo "bbbbb" > b.txt;
      - name: Upload Compressed Files
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: coverage-files
          path: |
            ${{ github.workspace }}/a.txt
            ${{ github.workspace }}/b.txt
            ${{ github.workspace }}/c.txt
          retention-days: 7
