# Define workflow name.
name: Test

on:
  workflow_dispatch:

jobs:
  matrixone-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hostname
        run: |
          sudo hostnamectl hostname matrixone-upgrade-runner;
          hostname;
