# Define workflow name.
name: Test

on:
  workflow_dispatch:

jobs:
  matrixone-ci:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          cmake --version;
      - name: Get CMake
        uses: symbitic/install-cmake@master
      - run: |
          cmake --version;
      - uses: actions/checkout@v4
        with:
          repository: matrixorigin/matrixone
          ref: main
      - run: |
          make build;
