# Define workflow name.
name: Test

on:
  workflow_dispatch:

jobs:
  matrixone-ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
    
      - uses: beyondstorage/setup-hdfs@master
        with:
          hdfs-version: '3.3.1'
    
      - run: curl ${{ env.HDFS_NAMENODE_ADDR }}
