# Define workflow name.
name: Test

on:
  workflow_dispatch:

jobs:
  matrixone-ci:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          cmake --version;
      - name: Get CMake
        uses: symbitic/install-cmake@master
      - run: |
          cmake --version;
      - uses: actions/checkout@v4
        with:
          repository: matrixorigin/matrixone
          ref: main
      - name: Setup Env
        uses: matrixorigin/CI/actions/setup-env@modify-setup-go
        with: 
          go-version: ""
          go-version-file: ${{ github.workspace }}/go.mod
